In [ ]:
# -*- coding: utf-8 -*-
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup

HTML_PARSER   = "html.parser"
USER_AGENT    = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'
HEADERS       = {'User-Agent': USER_AGENT}
MOVIE_ID_URL  = 'https://www.imdb.com/title/'
head = ["imdb_id", "budget"]
fileName = '100_5093_lost_budget 拷貝.csv'

def title(file):
	count = 0
	df = pd.read_csv(file)
	for i in range(4020, 5864):
		print(i, df.imdb_id[i])
		data_list = Movie(df.imdb_id[i])
		df_write = pd.DataFrame(data_list , columns = head)
		df_write.to_csv("budget4020_to_5864.csv", mode='a', header=False)
		print('count: ',count)
		print(i,"write ok")
		count += 1

def Movie(title):
	data_list = []
	movie_req = requests.get(MOVIE_ID_URL+title, headers = HEADERS)
	if movie_req.status_code == requests.codes.ok:
		print('URL OK')
		soup = BeautifulSoup(movie_req.content, HTML_PARSER)
		if len(soup.select('div.txt-block')) == 0:
			budget = 'no data'
		else:
			for i in range(0, len(soup.select('div.txt-block'))):
				if 'Budget:' in soup.select('div.txt-block')[i].text:
					budget = soup.select('div.txt-block')[i].text.strip().replace('Budget:', '')
					budget = budget.replace('(estimated)','').strip()
					break
				else:
					budget = 'no data'
			print(budget)
	data_list.append([title, budget])
	return data_list

if __name__ == '__main__':
	start = time.time()
	title(fileName)
	print('All cost',time.time()-start)

4020 tt5144744
URL OK
count:  0
4020 write ok
4021 tt5599906
URL OK
no data
count:  1
4021 write ok
4022 tt4111826
URL OK
no data
count:  2
4022 write ok
4023 tt4322510
URL OK
no data
count:  3
4023 write ok
4024 tt5258306
URL OK
no data
count:  4
4024 write ok
4025 tt4741466
URL OK
no data
count:  5
4025 write ok
4026 tt3352034
URL OK
no data
count:  6
4026 write ok
4027 tt4625334
URL OK
CAD 1,500,000
count:  7
4027 write ok
4028 tt6076366
URL OK
no data
count:  8
4028 write ok
4029 tt1098210
URL OK
no data
count:  9
4029 write ok
4030 tt5452964
URL OK
no data
count:  10
4030 write ok
4031 tt5893480
URL OK
no data
count:  11
4031 write ok
4032 tt6107412
URL OK
no data
count:  12
4032 write ok
4033 tt5752360
URL OK
no data
count:  13
4033 write ok
4034 tt4832248
URL OK
no data
count:  14
4034 write ok
4035 tt4768926
URL OK
no data
count:  15
4035 write ok
4036 tt5495270
URL OK
no data
count:  16
4036 write ok
4037 tt5959952
URL OK
no data
count:  17
4037 write ok
4038 tt5451054
URL OK
no data
count:  18
4038 write ok
4039 tt4771932
URL OK
€1,200,000
count:  19
4039 write ok
4040 tt5026204
URL OK
no data
count:  20
4040 write ok
4041 tt5649762
URL OK
no data
count:  21
4041 write ok
4042 tt4467176
URL OK
no data
count:  22
4042 write ok
4043 tt6087086
URL OK
INR 1,000,000,000
count:  23
4043 write ok
4044 tt6188658
URL OK
no data
count:  24
4044 write ok
4045 tt5743858
URL OK
INR 60,000,000
count:  25
4045 write ok
4046 tt3339534
URL OK
no data
count:  26
4046 write ok
4047 tt2582498
URL OK
no data
count:  27
4047 write ok
4048 tt4840098
URL OK
no data
count:  28
4048 write ok
4049 tt6401072
URL OK
no data
count:  29
4049 write ok
4050 tt6027344
URL OK
no data
count:  30
4050 write ok
4051 tt5278464
URL OK
no data
count:  31
4051 write ok
4052 tt0103266
URL OK
no data
count:  32
4052 write ok
4053 tt3319844
URL OK
no data
count:  33
4053 write ok
4054 tt5535814
URL OK
no data
count:  34
4054 write ok
4055 tt3044562
URL OK
no data
count:  35
4055 write ok
4056 tt6287174
URL OK
€3,560,000
count:  36
4056 write ok
4057 tt5272796
URL OK
no data
count:  37
4057 write ok
4058 tt5843670
URL OK
no data
count:  38
4058 write ok
4059 tt2759372
URL OK
no data
count:  39
4059 write ok
4060 tt4494094
URL OK
no data
count:  40
4060 write ok
4061 tt6258486
URL OK
no data
count:  41
4061 write ok
4062 tt5525790
URL OK
£37,000,000
count:  42
4062 write ok
4063 tt3445580
URL OK
no data
count:  43
4063 write ok
4064 tt5226330
URL OK
AUD 1,400,000
count:  44
4064 write ok
4065 tt3865238
URL OK
no data
count:  45
4065 write ok
4066 tt3704700
URL OK
no data
count:  46
4066 write ok
4067 tt3917908
URL OK
no data
count:  47
4067 write ok
4068 tt5914350
URL OK
no data
count:  48
4068 write ok
4069 tt3177086
URL OK
no data
count:  49
4069 write ok
4070 tt4983736
URL OK
INR 200,000,000
count:  50
4070 write ok
4071 tt4673790
URL OK
no data
count:  51
4071 write ok
4072 tt5314450
URL OK
no data
count:  52
4072 write ok
4073 tt4538016
URL OK
€3,973,431
count:  53
4073 write ok
4074 tt5146068
URL OK
no data
count:  54
4074 write ok
4075 tt1262990
URL OK
no data
count:  55
4075 write ok
4076 tt5297140
URL OK
$691,650
count:  56
4076 write ok
4077 tt5086772
URL OK
no data
count:  57
4077 write ok
4078 tt0313965
URL OK
no data
count:  58
4078 write ok
4079 tt4058122
URL OK
no data
count:  59
4079 write ok
4080 tt5988898
URL OK
no data
count:  60
4080 write ok
4081 tt4010862
URL OK
no data
count:  61
4081 write ok
4082 tt6385842
URL OK
no data
count:  62
4082 write ok
4083 tt3842614
URL OK
no data
count:  63
4083 write ok
4084 tt5765144
URL OK
€1,300,000
count:  64
4084 write ok
4085 tt6059142
URL OK
£0
count:  65
4085 write ok
4086 tt5287852
URL OK
no data
count:  66
4086 write ok
4087 tt4675030
URL OK
INR 30,000,000
count:  67
4087 write ok
4088 tt5912454
URL OK
no data
count:  68
4088 write ok
4089 tt5698496
URL OK
no data
count:  69
4089 write ok
4090 tt4213832
URL OK
no data
count:  70
4090 write ok
4091 tt5569614
URL OK
no data
count:  71
4091 write ok
4092 tt6448498
URL OK
no data
count:  72
4092 write ok
4093 tt5954088
URL OK
no data
count:  73
4093 write ok
4094 tt5535726
URL OK
no data
count:  74
4094 write ok
4095 tt5747466
URL OK
no data
count:  75
4095 write ok
4096 tt0317352
URL OK
no data
count:  76
4096 write ok
4097 tt6333066
URL OK
no data
count:  77
4097 write ok
4098 tt4647900
URL OK
no data
count:  78
4098 write ok
4099 tt4715652
URL OK
no data
count:  79
4099 write ok
4100 tt5341446
URL OK
no data
count:  80
4100 write ok
4101 tt5328784
URL OK
INR 100,000,000
count:  81
4101 write ok
4102 tt5719232
URL OK
no data
count:  82
4102 write ok
4103 tt5021712
URL OK
no data
count:  83
4103 write ok
4104 tt5182856
URL OK
no data
count:  84
4104 write ok
4105 tt5378224
URL OK
no data
count:  85
4105 write ok
4106 tt4589186
URL OK
no data
count:  86
4106 write ok
4107 tt5695668
URL OK
no data
count:  87
4107 write ok
4108 tt4911876
URL OK
$1,500,000
count:  88
4108 write ok
4109 tt2170427
URL OK
no data
count:  89
4109 write ok
4110 tt1558259
URL OK
no data
count:  90
4110 write ok
4111 tt4159698
URL OK
no data
count:  91
4111 write ok
4112 tt6211580
URL OK
no data
count:  92
4112 write ok
4113 tt3778010
URL OK
no data
count:  93
4113 write ok
4114 tt4222028
URL OK
no data
count:  94
4114 write ok
4115 tt3886508
URL OK
no data
count:  95
4115 write ok
4116 tt5829040
URL OK
no data
count:  96
4116 write ok
4117 tt2355695
URL OK
no data
count:  97
4117 write ok
4118 tt3489996
URL OK
$2,000,000
count:  98
4118 write ok
4119 tt4118932
URL OK
no data
count:  99
4119 write ok
4120 tt5070130
URL OK
no data
count:  100
4120 write ok
4121 tt4872260
URL OK
no data
count:  101
4121 write ok
4122 tt4303340
URL OK
€1,254,470
count:  102
4122 write ok
4123 tt1993050
URL OK
no data
count:  103
4123 write ok
4124 tt5842022
URL OK
no data
count:  104
4124 write ok
4125 tt5783124
URL OK
€180,000
count:  105
4125 write ok
4126 tt6098134
URL OK
no data
count:  106
4126 write ok
4127 tt5458566
URL OK
no data
count:  107
4127 write ok
4128 tt5851492
URL OK
INR 3,000,000
count:  108
4128 write ok
4129 tt5016028
URL OK
no data
count:  109
4129 write ok
4130 tt4637050
URL OK
no data
count:  110
4130 write ok
4131 tt5278592
URL OK
no data
count:  111
4131 write ok
4132 tt5225338
URL OK
no data
count:  112
4132 write ok
4133 tt5830248
URL OK
no data
count:  113
4133 write ok
4134 tt5039088
URL OK
no data
count:  114
4134 write ok
4135 tt5341052
URL OK
no data
count:  115
4135 write ok
4136 tt5980798
URL OK
no data
count:  116
4136 write ok
4137 tt5973364
URL OK
no data
count:  117
4137 write ok
4138 tt5340516
URL OK
no data
count:  118
4138 write ok
4139 tt0279187
URL OK
no data
count:  119
4139 write ok
4140 tt5347158
URL OK
$500,000
count:  120
4140 write ok
4141 tt6088634
URL OK
no data
count:  121
4141 write ok
4142 tt4641264
URL OK
no data
count:  122
4142 write ok
4143 tt2091245
URL OK
$1,500,000
count:  123
4143 write ok
4144 tt5788462
URL OK
no data
count:  124
4144 write ok
4145 tt3127902
URL OK
no data
count:  125
4145 write ok
4146 tt5803868
URL OK
no data
count:  126
4146 write ok
4147 tt4424722
URL OK
no data
count:  127
4147 write ok
4148 tt5191938
URL OK
no data
count:  128
4148 write ok
4149 tt5065762
URL OK
no data
count:  129
4149 write ok
4150 tt0119505
URL OK
no data
count:  130
4150 write ok
4151 tt8016466
URL OK
no data
count:  131
4151 write ok
4152 tt6197028
URL OK
no data
count:  132
4152 write ok
4153 tt6264782
URL OK
no data
count:  133
4153 write ok
4154 tt4118606
URL OK
no data
count:  134
4154 write ok
4155 tt0039174
URL OK
no data
count:  135
4155 write ok
4156 tt5717110
URL OK
no data
count:  136
4156 write ok
4157 tt4872078
URL OK
no data
count:  137
4157 write ok
4158 tt5112578
URL OK
no data
count:  138
4158 write ok
4159 tt5147214
URL OK
no data
count:  139
4159 write ok
4160 tt4662420
URL OK
no data
count:  140
4160 write ok
4161 tt5633706
URL OK
no data
count:  141
4161 write ok
4162 tt5778060
URL OK
no data
count:  142
4162 write ok
4163 tt6680116
URL OK
no data
count:  143
4163 write ok
4164 tt5599702
URL OK
no data
count:  144
4164 write ok
4165 tt6421366
URL OK
no data
count:  145
4165 write ok
4166 tt6114606
URL OK
no data
count:  146
4166 write ok
4167 tt5829116

URL OK
$5,000,000
count:  147
4167 write ok
4168 tt6562798
URL OK
no data
count:  148
4168 write ok
4169 tt4532818
URL OK
no data
count:  149
4169 write ok
4170 tt5900208
URL OK
no data
count:  150
4170 write ok
4171 tt4836736
URL OK
no data
count:  151
4171 write ok
4172 tt5840448
URL OK
no data
count:  152
4172 write ok
4173 tt6476532
URL OK
INR 4,500,000
count:  153
4173 write ok
4174 tt4699444
URL OK
no data
count:  154
4174 write ok
4175 tt4373956
URL OK
no data
count:  155
4175 write ok
4176 tt5599818
URL OK
TRL 500
count:  156
4176 write ok
4177 tt6447766
URL OK
no data
count:  157
4177 write ok
4178 tt4637878
URL OK
no data
count:  158
4178 write ok
4179 tt2814628
URL OK
no data
count:  159
4179 write ok
4180 tt5068628
URL OK
no data
count:  160
4180 write ok
4181 tt5335128
URL OK
no data
count:  161
4181 write ok
4182 tt5275838
URL OK
no data
count:  162
4182 write ok
4183 tt5718290
URL OK
no data
count:  163
4183 write ok
4184 tt5271442
URL OK
no data
count:  164
4184 write ok
4185 tt4741774
URL OK
no data
count:  165
4185 write ok
4186 tt6122194
URL OK
no data
count:  166
4186 write ok
4187 tt4528454
URL OK
£1,000,000
count:  167
4187 write ok
4188 tt5936692
URL OK
no data
count:  168
4188 write ok
4189 tt3424690
URL OK
no data
count:  169
4189 write ok
4190 tt5852632
URL OK
no data
count:  170
4190 write ok
4191 tt4196832
URL OK
no data
count:  171
4191 write ok
4192 tt6271110
URL OK
no data
count:  172
4192 write ok
4193 tt5254640
URL OK
no data
count:  173
4193 write ok
4194 tt4072326
URL OK
$20,000,000
count:  174
4194 write ok
4195 tt0120550
URL OK
no data
count:  175
4195 write ok
4196 tt3037164
URL OK
no data
count:  176
4196 write ok
4197 tt5281700
URL OK
$7,500,000
count:  177
4197 write ok
4198 tt3322892
URL OK
no data
count:  178
4198 write ok
4199 tt4552524
URL OK
no data
count:  179
4199 write ok
4200 tt1847672
URL OK
no data
count:  180
4200 write ok
4201 tt4555674
URL OK
no data
count:  181
4201 write ok
4202 tt4229298
URL OK
no data
count:  182
4202 write ok
4203 tt4777584
URL OK
no data
count:  183
4203 write ok
4204 tt5880296
URL OK
no data
count:  184
4204 write ok
4205 tt6333070
URL OK
no data
count:  185
4205 write ok
4206 tt4677924
URL OK
$5,000,000
count:  186
4206 write ok
4207 tt6054058
URL OK
INR 600,000,000
count:  187
4207 write ok
4208 tt4728386
URL OK
AUD 1,300,000
count:  188
4208 write ok
4209 tt4485246
URL OK
$700,000
count:  189
4209 write ok
4210 tt2787570
URL OK
€5,000,000
count:  190
4210 write ok
4211 tt5777808
URL OK
TRL 1,350,000
count:  191
4211 write ok
4212 tt4990516
URL OK
no data
count:  192
4212 write ok
4213 tt5323640
URL OK
no data
count:  193
4213 write ok
4214 tt6611028
URL OK
AUD 400,000
count:  194
4214 write ok
4215 tt3663020
URL OK
no data
count:  195
4215 write ok
4216 tt5439426
URL OK
NZD 100,000
count:  196
4216 write ok
4217 tt5333612
URL OK
no data
count:  197
4217 write ok
4218 tt5625152
URL OK
no data
count:  198
4218 write ok
4219 tt6725484
URL OK
no data
count:  199
4219 write ok
4220 tt5074552
URL OK
INR 80,000,000
count:  200
4220 write ok
4221 tt3384350
URL OK
no data
count:  201
4221 write ok
4222 tt4419364
URL OK
no data
count:  202
4222 write ok
4223 tt6370266
URL OK
no data
count:  203
4223 write ok
4224 tt4536768
URL OK
no data
count:  204
4224 write ok
4225 tt5833730
URL OK
no data
count:  205
4225 write ok
4226 tt4181270
URL OK
no data
count:  206
4226 write ok
4227 tt5096628
URL OK
no data
count:  207
4227 write ok
4228 tt3409848
URL OK
no data
count:  208
4228 write ok
4229 tt6317052
URL OK
no data
count:  209
4229 write ok
4230 tt5450570
URL OK
no data
count:  210
4230 write ok
4231 tt4680196
URL OK
no data
count:  211
4231 write ok
4232 tt5290620
URL OK
no data
count:  212
4232 write ok
4233 tt5298558
URL OK
no data
count:  213
4233 write ok
4234 tt0421994
URL OK
$7,900,000
count:  214
4234 write ok
4235 tt5606268
URL OK
no data
count:  215
4235 write ok
4236 tt4789160
URL OK
no data
count:  216
4236 write ok
4237 tt5820812
URL OK
no data
count:  217
4237 write ok
4238 tt3564574
URL OK
no data
count:  218
4238 write ok
4239 tt5925968
URL OK
no data
count:  219
4239 write ok
4240 tt5536398
URL OK
no data
count:  220
4240 write ok
4241 tt4627352
URL OK
no data
count:  221
4241 write ok
4242 tt6107852
URL OK
no data
count:  222
4242 write ok
4243 tt4875150
URL OK
no data
count:  223
4243 write ok
4244 tt5186236
URL OK
no data
count:  224
4244 write ok
4245 tt5252396
URL OK
no data
count:  225
4245 write ok
4246 tt5943306
URL OK
no data
count:  226
4246 write ok
4247 tt3608930
URL OK
no data
count:  227
4247 write ok
4248 tt5975354
URL OK
no data
count:  228
4248 write ok
4249 tt5389922
URL OK
no data
count:  229
4249 write ok
4250 tt6056644
URL OK
no data
count:  230
4250 write ok
4251 tt6299040
URL OK
no data
count:  231
4251 write ok
4252 tt5975242
URL OK
no data
count:  232
4252 write ok
4253 tt6712026
URL OK
no data
count:  233
4253 write ok
4254 tt5756188
URL OK
€350,000
count:  234
4254 write ok
4255 tt6599064
URL OK
no data
count:  235
4255 write ok
4256 tt2610248
URL OK
no data
count:  236
4256 write ok
4257 tt5011242
URL OK
€1,000,000
count:  237
4257 write ok
4258 tt6340112
URL OK
no data
count:  238
4258 write ok
4259 tt5599692
URL OK
no data
count:  239
4259 write ok
4260 tt5598206
URL OK
no data
count:  240
4260 write ok
4261 tt5265960
URL OK
no data
count:  241
4261 write ok
4262 tt5713232
URL OK
no data
count:  242
4262 write ok
4263 tt5804946
URL OK
no data
count:  243
4263 write ok
4264 tt6338476
URL OK
no data
count:  244
4264 write ok
4265 tt5755912
URL OK
no data
count:  245
4265 write ok
4266 tt5432624
URL OK
no data
count:  246
4266 write ok
4267 tt7236640
URL OK
no data
count:  247
4267 write ok
4268 tt5253282
URL OK
no data
count:  248
4268 write ok
4269 tt5822414
URL OK
no data
count:  249
4269 write ok
4270 tt4671772
URL OK
no data
count:  250
4270 write ok
4271 tt4442604
URL OK
no data
count:  251
4271 write ok
4272 tt4382824
URL OK
no data
count:  252
4272 write ok
4273 tt3853830
URL OK
$1,250,000
count:  253
4273 write ok
4274 tt4265508
URL OK
no data
count:  254
4274 write ok
4275 tt4628826
URL OK
no data
count:  255
4275 write ok
4276 tt4747848
URL OK
€810,580
count:  256
4276 write ok
4277 tt5352802
URL OK
no data
count:  257
4277 write ok
4278 tt5821256
URL OK
no data
count:  258
4278 write ok
4279 tt5462326
URL OK
no data
count:  259
4279 write ok
4280 tt5597946
URL OK
no data
count:  260
4280 write ok
4281 tt5755796
URL OK
no data
count:  261
4281 write ok
4282 tt5039860
URL OK
€15,000,000
count:  262
4282 write ok
4283 tt4381236
URL OK
no data
count:  263
4283 write ok
4284 tt5937296
URL OK
no data
count:  264
4284 write ok
4285 tt0116631
URL OK
no data
count:  265
4285 write ok
4286 tt4446472
URL OK
no data
count:  266
4286 write ok
4287 tt5279204
URL OK
no data
count:  267
4287 write ok
4288 tt5538568
URL OK
no data
count:  268
4288 write ok
4289 tt4054654
URL OK
no data
count:  269
4289 write ok
4290 tt3913194
URL OK
no data
count:  270
4290 write ok
4291 tt3726012
URL OK
no data
count:  271
4291 write ok
4292 tt2417712
URL OK
no data
count:  272
4292 write ok
4293 tt5892354
URL OK
no data
count:  273
4293 write ok
4294 tt5275866
URL OK
no data
count:  274
4294 write ok
4295 tt5652594
URL OK
no data
count:  275
4295 write ok
4296 tt3481634
URL OK
no data
count:  276
4296 write ok
4297 tt3551954
URL OK
no data
count:  277
4297 write ok
4298 tt4451458
URL OK
no data
count:  278
4298 write ok
4299 tt5270366
URL OK
INR 40,000,000
count:  279
4299 write ok
4300 tt4378066
URL OK
no data
count:  280
4300 write ok
4301 tt5173032
URL OK
no data
count:  281
4301 write ok
4302 tt4061944
URL OK
no data
count:  282
4302 write ok
4303 tt5326138
URL OK
no data
count:  283
4303 write ok
4304 tt5129682
URL OK
no data
count:  284
4304 write ok
4305 tt4779036
URL OK
no data
count:  285
4305 write ok
4306 tt6125690
URL OK
€2,000,000
count:  286
4306 write ok
4307 tt6170954
URL OK
INR 290,000,000
count:  287
4307 write ok
4308 tt4819510
URL OK
no data
count:  288
4308 write ok
4309 tt5084198
URL OK
no data
count:  289
4309 write ok
4310 tt6544850
URL OK
no data
count:  290
4310 write ok
4311 tt5649856
URL OK
no data
count:  291
4311 write ok
4312 tt2401585

URL OK
no data
count:  292
4312 write ok
4313 tt4572820
URL OK
no data
count:  293
4313 write ok
4314 tt4467626
URL OK
no data
count:  294
4314 write ok
4315 tt4687410
URL OK
no data
count:  295
4315 write ok
4316 tt2474932
URL OK
no data
count:  296
4316 write ok
4317 tt6194934
URL OK
no data
count:  297
4317 write ok
4318 tt0102744
URL OK
$20,000,000
count:  298
4318 write ok
4319 tt5917052
URL OK
CAD 4,000,000
count:  299
4319 write ok
4320 tt5475022
URL OK
no data
count:  300
4320 write ok
4321 tt6677500
URL OK
no data
count:  301
4321 write ok
4322 tt4929038
URL OK
no data
count:  302
4322 write ok
4323 tt3584954
URL OK
€766,000
count:  303
4323 write ok
4324 tt4372736
URL OK
$1,200,000
count:  304
4324 write ok
4325 tt5556784
URL OK
no data
count:  305
4325 write ok
4326 tt2262315
URL OK
no data
count:  306
4326 write ok
4327 tt2923088
URL OK
no data
count:  307
4327 write ok
4328 tt5129510
URL OK
no data
count:  308
4328 write ok
4329 tt7399726
URL OK